import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Layout({children}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Tareas de JCC</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.png"/>
            </Head>

            <main className={styles.main}>
                <div className={styles.grid}>
                    Tarea APP
                </div>
                <div className={styles.grid}>
                    Agregar Tarea
                </div>

                <h1 className="text-6xl font-boldt first-letter:text-[#0070f3]">
                    Bienvenido a TAREAS App!
                </h1>

                <p className={styles.description}>
                    Comience por editar{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    {children}
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Impulsado por{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Logo-Vercel" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}